name: dummy service
team: some team
project: Project X

dependencies:
  - name: Some Service 2
  - name: Some Service 3

external_resources:
  - name: Legacy DB
  - name: something else

verfifiers:
  - smoke_tests:
      - name: Simple Check
        runner: http_ok_verification
        url: http://127.0.0.1/
