name: dummy service
team: customer team
project: test
description: This service really doesn't do a lot...

dependencies:
  - Some Service 2
  - Some Service 3

external_resources:
  - Legacy DB
  - something else
